{
 "title": "JVM",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nginx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nginx_connections_handled{instance=\"192.168.2.169:9113\"}"
    }
   ]
  },
  {
   "title": "Node",
   "type": "timeseries",
   "description": "диск",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_disk_io_now{job=\"host-node\"}"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "postgres_exporter_build_info{job=\"postgres\"}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"neoflex\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"boltdb_reads_total\" or r[\"_measurement\"] == \"boltdb_writes_total\" or r[\"_measurement\"] == \"go_gc_duration_seconds\" or r[\"_measurement\"] == \"go_info\" or r[\"_measurement\"] == \"go_goroutines\" or r[\"_measurement\"] == \"go_memstats_alloc_bytes\" or r[\"_measurement\"] == \"go_memstats_alloc_bytes_total\" or r[\"_measurement\"] == \"task_scheduler_current_execution\" or r[\"_measurement\"] == \"task_scheduler_execute_delta\" or r[\"_measurement\"] == \"task_scheduler_schedule_delay\" or r[\"_measurement\"] == \"service_org_new_call_total\" or r[\"_measurement\"] == \"service_org_duration\" or r[\"_measurement\"] == \"service_onboard_new_duration\" or r[\"_measurement\"] == \"http_query_request_count\" or r[\"_measurement\"] == \"http_query_request_bytes\" or r[\"_measurement\"] == \"http_api_requests_total\" or r[\"_measurement\"] == \"go_threads\" or r[\"_measurement\"] == \"go_memstats_heap_released_bytes\" or r[\"_measurement\"] == \"go_memstats_heap_idle_bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "grad" } },
   "targets": [
    {
     "expr": "prometheus_http_requests_total{instance=\"192.168.2.169:9090\"}"
    }
   ]
  },
  {
   "title": "InfluxDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"neoflex\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"boltdb_reads_total\" or r[\"_measurement\"] == \"go_goroutines\" or r[\"_measurement\"] == \"go_memstats_alloc_bytes\" or r[\"_measurement\"] == \"go_memstats_frees_total\" or r[\"_measurement\"] == \"go_memstats_buck_hash_sys_bytes\" or r[\"_measurement\"] == \"go_memstats_alloc_bytes_total\" or r[\"_measurement\"] == \"go_info\" or r[\"_measurement\"] == \"boltdb_writes_total\" or r[\"_measurement\"] == \"go_gc_duration_seconds\" or r[\"_measurement\"] == \"go_memstats_other_sys_bytes\" or r[\"_measurement\"] == \"go_memstats_sys_bytes\" or r[\"_measurement\"] == \"influxdb_uptime_seconds\" or r[\"_measurement\"] == \"influxdb_users_total\" or r[\"_measurement\"] == \"service_org_new_duration\" or r[\"_measurement\"] == \"service_org_new_error_total\" or r[\"_measurement\"] == \"service_password_new_call_total\" or r[\"_measurement\"] == \"service_password_new_duration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"+Inf\" or r[\"_field\"] == \"0.05\" or r[\"_field\"] == \"0.01\" or r[\"_field\"] == \"0.005\" or r[\"_field\"] == \"0\" or r[\"_field\"] == \"count\" or r[\"_field\"] == \"gauge\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}